spring:
  application:
    name: NOTIFICATION-SERVICE
  boot:
    messages: "Hello from Notification Service"
  security:
    authentication:
      jwt:
        # openssl rand -base64 64
        base64-secret: ${SPRING_SECURITY_JWT_SECRET}
  kafka:
    bootstrap-servers: ${KAFKA_DEFAULT_HOST}:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
activation:
  link: http://api-gateway:9191/identity-service/api/v1/auth/activate?token=
  reset: http://api-gateway:9191/identity-service/api/v1/auth/reset-password?token=
server:
  port: ${NOTIFICATION_SERVICE_PORT}