spring:
  application:
    name: NOTIFICATION-SERVICE
  boot:
    messages: "Hello from Notification Service"
  mail:
    host: smtp.gmail.com
    port: 587
    username: "helpcenter.teamconnect@gmail.com"
    password: "bsds dumc xvtw hzcz"
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8087