spring:
  application:
    name: IDENTITY-SERVICE
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    authentication:
      jwt:
        # openssl rand -base64 64
        base64-secret: YTwQoI5e3OjbPsvbRgXFdbGAz3ML2jTezUQTD0CO82VOl/ZrzSyJvQ5b6t1YyS9bqiT4jA1bny2MhHn4RNcu9A==
        access-token-validity-in-seconds: 86400
        refresh-token-validity-in-seconds: 86400
  api:
    version: /api/v1
  boot:
    message: Hello , IDENTITY-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12760287
    username: sql12760287
    password: fF756YjrfP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8082

