spring:
  application:
    name: IDENTITY-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  security:
    authentication:
      jwt:
        # openssl rand -base64 64
        base64-secret: YTwQoI5e3OjbPsvbRgXFdbGAz3ML2jTezUQTD0CO82VOl/ZrzSyJvQ5b6t1YyS9bqiT4jA1bny2MhHn4RNcu9A==
        access-token-validity-in-seconds: 86400 # 1 day
        refresh-token-validity-in-seconds: 86400 # 1 day
