spring:
  application:
    name: IDENTITY-SERVICE
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    authentication:
      jwt:
        # openssl rand -base64 64
        base64-secret: ${SPRING_SECURITY_JWT_SECRET}
        access-token-validity-in-seconds: ${SPRING_SECURITY_JWT_EXPIRATION}
        access-token-active-in-seconds: ${SPRING_SECURITY_ACTIVE}
        refresh-token-validity-in-seconds: ${SPRING_SECURITY_JWT_EXPIRATION}
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_TEST}
            client-secret: ${GOOGLE_TEST}
  kafka:
    bootstrap-servers: ${KAFKA_DEFAULT_HOST}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: identity-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'
  api:
    version: /api/v1
  boot:
    message: Hello , IDENTITY-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true
  rabbitmq:
    host: ${RABBITMQ_DEFAULT_HOST}
    port: ${RABBITMQ_DEFAULT_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
cors-gateway:
  host: http://localhost:9191
server:
  port: ${IDENTITY_SERVICE_PORT}
  forward-headers-strategy: framework

