spring:
  application:
    name: SERVICE-REGISTRY
server:
  port: ${SERVICE_REGISTRY_PORT}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

#password google: bsds dumc xvtw hzcz