spring:
  application:
    name: SERVICE-REGISTRY
  boot:
    message: Hello , SERVICE-REGISTRY from dev
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

#password google: bsds dumc xvtw hzcz