image: docker:24.0.5

services:
  - docker:24.0.5-dind

before_script:
  - docker info
  - apk add --no-cache curl
  - curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.36.0/pack-v0.36.0-linux.tgz" |  tar -C /usr/local/bin/ --no-same-owner -xzv pack
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

stages:
  - build
  - deploy

build_identity_service:
  stage: build
  script:
    - echo "Building identity-service with Buildpacks..."
    - cd identity-service
    - pack build integrationninjas/identity-service:$CI_COMMIT_SHA --path . --builder paketobuildpacks/builder:base --tag integrationninjas/identity-service:$CI_COMMIT_SHA
    - docker images
    - docker tag integrationninjas/identity-service:$CI_COMMIT_SHA ashleynguci1072003/01-ecommerce-backend-identity-service:identity-service-$CI_COMMIT_SHA
    - docker push ashleynguci1072003/01-ecommerce-backend-identity-service:identity-service-$CI_COMMIT_SHA
  only:
    - staging

build_cart_service:
  stage: build
  script:
    - echo "Building cart-service with Buildpacks..."
    - cd cart-service
    - pack build integrationninjas/cart-service:$CI_COMMIT_SHA --path . --builder paketobuildpacks/builder:base --tag integrationninjas/cart-service:$CI_COMMIT_SHA
    - docker images
    - docker tag integrationninjas/cart-service:$CI_COMMIT_SHA ashleynguci1072003/01-ecommerce-backend-cart-service:cart-service-$CI_COMMIT_SHA
    - docker push ashleynguci1072003/01-ecommerce-backend-cart-service:cart-service-$CI_COMMIT_SHA
  only:
    - staging

build_api_gateway:
  stage: build
  script:
    - echo "Building api-gateway with Buildpacks..."
    - cd api-gateway
    - pack build integrationninjas/api-gateway:$CI_COMMIT_SHA --path . --builder paketobuildpacks/builder:base --tag integrationninjas/api-gateway:$CI_COMMIT_SHA
    - docker images
    - docker tag integrationninjas/api-gateway:$CI_COMMIT_SHA ashleynguci1072003/01-ecommerce-backend-api-gateway:api-gateway-$CI_COMMIT_SHA
    - docker push ashleynguci1072003/01-ecommerce-backend-api-gateway:api-gateway-$CI_COMMIT_SHA
  only:
    - staging
build_service_registry:
  stage: build
  script:
    - echo "Building service-registry with Buildpacks..."
    - cd service-registry
    - pack build integrationninjas/service-registry:$CI_COMMIT_SHA --path . --builder paketobuildpacks/builder:base --tag integrationninjas/service-registry:$CI_COMMIT_SHA
    - docker images
    - docker tag integrationninjas/service-registry:$CI_COMMIT_SHA ashleynguci1072003/01-ecommerce-backend-service-registry:service-registry-$CI_COMMIT_SHA
    - docker push ashleynguci1072003/01-ecommerce-backend-service-registry:service-registry-$CI_COMMIT_SHA
  only:
    - staging
build_product_service:
  stage: build
  script:
    - echo "Building product-service with Buildpacks..."
    - cd product-service
    - pack build integrationninjas/product-service:$CI_COMMIT_SHA --path . --builder paketobuildpacks/builder:base --tag integrationninjas/product-service:$CI_COMMIT_SHA
    - docker images
    - docker tag integrationninjas/product-service:$CI_COMMIT_SHA ashleynguci1072003/01-ecommerce-backend-product-service:product-service-$CI_COMMIT_SHA
    - docker push ashleynguci1072003/01-ecommerce-backend-product-service:product-service-$CI_COMMIT_SHA
  only:
    - staging

deploy_job:
  stage: deploy
  script:
    - echo "Deploying identity-service..."
  only:
    - staging

