version: '3.8'
services:
  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
    ports:
      - "9089:8080"
    depends_on:
      - kafka
    networks:
      - backend
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: sapassword
      MYSQL_DATABASE: identity_db
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: 'rabbitmq:4.0.5'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

  identity-service:
    image: 'ashleynguci1072003/01-ecommerce-backend-identity-service:identity-service-1c933d873861e644b8b62d9c76062af3e8fb68d1'
    container_name: identity-service
    ports:
      - '8082:8082'
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: identity_db
      DB_USER: root
      DB_PASSWORD: sapassword
    depends_on:
      - mysql
    networks:
      - backend

  cart-service:
    image: 'ashleynguci1072003/01-ecommerce-backend-cart-service:cart-service-1c933d873861e644b8b62d9c76062af3e8fb68d1'
    container_name: cart-service
    ports:
      - '8084:8084'
    networks:
      - backend

volumes:
  mysql_data:


networks:
  backend:
    driver: bridge
