version: '3.8'
services:
  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - backend

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
    ports:
      - "9089:8080"
    depends_on:
      - kafka
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: sapassword
      MYSQL_DATABASE: identity_db
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  rabbitmq:
    image: 'rabbitmq:4.0.5'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

  identity-service:
    image: 'ashleynguci1072003/01-ecommerce-backend-identity-service:identity-service-41a1557be61e6dec2a6a6e7ee3e93a6cf041b5be'
    container_name: identity-service
    ports:
      - '8082:8082'
    environment:
      - SPRING_DATASOURCE_URL= jdbc:mysql://mysql:3306/identity_db
      - SPRING_DATASOURCE_USERNAME= root
      - SPRING_DATASOURCE_PASSWORD= sapassword
    depends_on:
      - mysql
    networks:
      - backend

  cart-service:
    image: 'ashleynguci1072003/01-ecommerce-backend-cart-service:cart-service-41a1557be61e6dec2a6a6e7ee3e93a6cf041b5be'
    container_name: cart-service
    ports:
      - '8084:8084'
    networks:
      - backend

  product-service:
    image: 'ashleynguci1072003/01-ecommerce-backend-product-service:product-service-9f727f5b5e5e7b90e06586ddafbcd0b4fb11d4cd'
    container_name: product-service
    ports:
      - '8083:8083'
    networks:
      - backend

  order-service:
    image: 'ashleynguci1072003/01-ecommerce-backend-order-service:order-service-9f727f5b5e5e7b90e06586ddafbcd0b4fb11d4cd'
    container_name: order-service
    ports:
      - '8085:8085'
    networks:
      - backend

  payment-service:
    image: 'ashleynguci1072003/01-ecommerce-backend-payment-service:payment-service-9f727f5b5e5e7b90e06586ddafbcd0b4fb11d4cd'
    container_name: payment-service
    ports:
      - '8086:8086'
    networks:
      - backend

  notification-service:
    image: 'ashleynguci1072003/01-ecommerce-backend-notification-service:notification-service-9f727f5b5e5e7b90e06586ddafbcd0b4fb11d4cd'
    container_name: notification-service
    ports:
      - '8087:8087'
    networks:
      - backend

  config-server:
    image: 'ashleynguci1072003/01-ecommerce-backend-config-server:config-server-9f727f5b5e5e7b90e06586ddafbcd0b4fb11d4cd'
    container_name: config-server
    ports:
      - '8888:8888'
    networks:
      - backend

  service-registry:
    image: 'ashleynguci1072003/01-ecommerce-backend-service-registry:service-registry-41a1557be61e6dec2a6a6e7ee3e93a6cf041b5be'
    container_name: service-registry
    ports:
      - '8761:8761'
    networks:
      - backend

  api-gateway:
    image: 'ashleynguci1072003/01-ecommerce-backend-api-gateway:api-gateway-41a1557be61e6dec2a6a6e7ee3e93a6cf041b5be'
    container_name: api-gateway
    ports:
      - '9191:9191'
    networks:
      - backend
    depends_on:
      - service-registry
      - config-server
      - identity-service
      - product-service
      - order-service
      - payment-service
      - notification-service
      - cart-service


volumes:
  mysql_data:

networks:
  backend:
    driver: bridge


