spring:
  application:
    name: API-GATEWAY
  main:
    allow-circular-references: true

  cloud:
    gateway:
      #      routes:
      #        - id: EMPLOYEE-SERVICE
      #          uri: lb://EMPLOYEE-SERVICE
      #          predicates:
      #            - name: Path
      #              args:
      #                pattern: /api/employee-service/**
      #
      #        - id: DEPARTMENT-SERVICE
      #          uri: lb://DEPARTMENT-SERVICE
      #          predicates[0]:
      #            - name: Path
      #              args:
      #                pattern: /api/department-service/**
      excluded-url-pattern: "/employee-service/**"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
eureka:
  instance:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9191