spring:
  application:
    name: API-GATEWAY
  main:
    allow-circular-references: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cloud:
    gateway:
      #      routes:
      #        - id: EMPLOYEE-SERVICE
      #          uri: lb://EMPLOYEE-SERVICE
      #          predicates:
      #            - name: Path
      #              args:
      #                pattern: /api/employee-service/**
      #
      #        - id: DEPARTMENT-SERVICE
      #          uri: lb://DEPARTMENT-SERVICE
      #          predicates[0]:
      #            - name: Path
      #              args:
      #                pattern: /api/department-service/**
      #      excluded-url-pattern: "/employee-service/**"
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "http://next-client-hot:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 2
            redis-rate-limiter.requestedTokens: 1
            key-resolver: "#{@userKeyResolver}"
logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: ${API_GATEWAY_PORT}