spring:
  application:
    name: API-GATEWAY
  boot:
    message: Hello , API-GATEWAY from dev
  main:
    allow-circular-references: true

  cloud:
    gateway:
      httpclient:
        preserveHostHeader: true
      #      routes:
      #        - id: EMPLOYEE-SERVICE
      #          uri: lb://EMPLOYEE-SERVICE
      #          predicates:
      #            - name: Path
      #              args:
      #                pattern: /api/employee-service/**
      #
      #        - id: DEPARTMENT-SERVICE
      #          uri: lb://DEPARTMENT-SERVICE
      #          predicates[0]:
      #            - name: Path
      #              args:
      #                pattern: /api/department-service/**
      #      excluded-url-pattern: "/employee-service/**"
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000, http://localhost:3001, http://localhost:9191"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: gateway-service
        url: /v3/api-docs
      - name: product-service
        url: http://localhost:8083/v3/api-docs
      - name: payment-service
        url: http://localhost:8086/v3/api-docs
      - name: order-service
        url: http://localhost:8085/v3/api-docs
      - name: notification-service
        url: http://localhost:8087/v3/api-docs
      - name: identity-service
        url: http://localhost:8082/v3/api-docs
      - name: cart-service
        url: http://localhost:8084/v3/api-docs
server:
  port: 9191