spring:
  application:
    name: DEPARTMENT-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/department_db
#    username: root
#    password: sapassword
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#eureka:
#  instance:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#server:
#  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
