spring:
  application:
    name: ORDER-SERVICE
  boot:
    message: Hello World from Order Service
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: order-service
  security:
    authentication:
      jwt:
        # openssl rand -base64 64
        base64-secret: ZnrZWEcOiEHMQjUnLbs3eAvprDpEvX9sEl/6XqfiRMi6WGfXH5c+aObAPgfn6xcMe7l9G8oQz4y2o/g8gS1Rqw==
  kafka:
    bootstrap-servers: ${KAFKA_DEFAULT_HOST}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}
server:
  port: ${ORDER_SERVICE_PORT}




# password nosql: 8OWQ2rzxntvKxflL
# mongodb+srv://root:8OWQ2rzxntvKxflL@cluster0.hjsak.mongodb.net/
