spring:
  application:
    name: EMPLOYEE-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/employee_db
#    username: root
#    password: sapassword
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#eureka:
#  instance:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#server:
#  port: 8081
management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    web:
      exposure:
        include: "health"
    health:
      show-details: always
# Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        registerHealthIndicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
  # retry
  retry:
    instances:
      EMPLOYEE-SERVICE:
        max-attempts: 3
        wait-duration: 500


