spring:
  application:
    name: PRODUCT-SERVICE
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  boot:
    message: Hello , Product Service
  data:
    mongodb:
      uri: "mongodb+srv://root:8OWQ2rzxntvKxflL@cluster0.hjsak.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      database: product-service
eureka:
  instance:
    service-url:
      defaultZone: http://localhost:8761/eureka
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8083


# password nosql: 8OWQ2rzxntvKxflL
