spring:
  application:
    name: PRODUCT-SERVICE
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    host: ${RABBITMQ_DEFAULT_HOST}
    port: ${RABBITMQ_DEFAULT_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
  boot:
    message: Hello , Product Service

  kafka:
    bootstrap-servers: ${KAFKA_DEFAULT_HOST}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${KAFKA_GROUP_ID}
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: ${PRODUCT_MONGO_DB_NAME}
  security:
    authentication:
      jwt:
        # openssl rand -base64 64
        base64-secret: ${SPRING_SECURITY_JWT_SECRET}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}
management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
#cors-gateway:
#  host: http://localhost:9191
server:
  port: ${PRODUCT_SERVICE_PORT}
  forward-headers-strategy: framework


# password nosql: 8OWQ2rzxntvKxflL
