spring:
  application:
    name: CART-SERVICE
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest
  boot:
    message: Hello , Welcome to Cart Service
  security:
    authentication:
      jwt:
        # openssl rand -base64 64
        base64-secret: ${SPRING_SECURITY_JWT_SECRET}
  kafka:
    bootstrap-servers: ${KAFKA_DEFAULT_HOST}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: cart-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: cart-service
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
server:
  port: ${CART_SERVICE_PORT}
# password nosql: 8OWQ2rzxntvKxflL
# mongodb+srv://root:8OWQ2rzxntvKxflL@cluster0.hjsak.mongodb.net/