spring:
  application:
    name: CART-SERVICE
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest
  boot:
    message: Hello , Welcome to Cart Service
  kafka:
    bootstrap-servers: ${KAFKA_DEFAULT_HOST}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    mongodb:
      uri: ${MONGO_URL}
      database: cart-service
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}
server:
  port: ${CART_SERVICE_PORT}


# password nosql: 8OWQ2rzxntvKxflL
# mongodb+srv://root:8OWQ2rzxntvKxflL@cluster0.hjsak.mongodb.net/