spring:
  application:
    name: CART-SERVICE
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest
  boot:
    message: Hello , Welcome to Cart Service
  kafka:
    bootstrap-servers: kafka:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    mongodb:
      uri: "mongodb+srv://root:8OWQ2rzxntvKxflL@cluster0.hjsak.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      database: cart-service
  eureka:
    instance:
      service-url:
        defaultZone: http://service-registry:8761/eureka
      prefer-ip-address: true
server:
  port: 8084


# password nosql: 8OWQ2rzxntvKxflL
# mongodb+srv://root:8OWQ2rzxntvKxflL@cluster0.hjsak.mongodb.net/