spring:
  application:
    name: CART-SERVICE
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest
  boot:
    message: Hello , Welcome to Cart Service
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: cart-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'

  data:
    mongodb:
      uri: "mongodb+srv://root:8OWQ2rzxntvKxflL@cluster0.hjsak.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      database: cart-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8084

# password nosql: 8OWQ2rzxntvKxflL
# mongodb+srv://root:8OWQ2rzxntvKxflL@cluster0.hjsak.mongodb.net/